export const products = {
  okna: [
    {
      id: 1,
      name: 'AdamS PASSIV-LINE ULTRA',
      tagline: 'Dom pasywny – Uw do 0,54 W/(m²K)',
      description: 'System 6-komorowy z dociepleniem, głębokość 85mm. Wklejane szyby, wypełnienie pianą PU, wzmocnienia Ultradur (BASF). Pakiet 3- lub 4-szybowy z kryptonem.',
      features: ['85mm głębokość', 'Uw ≤ 0,54 W/(m²K)', '4-szybowy pakiet', 'Dom pasywny'],
      image: '/images/produkty/passiv_line_ultra.jpg',
      badge: 'BESTSELLER',
    },
    {
      id: 2,
      name: 'AdamS Passiv-Line PLUS',
      tagline: 'Energooszczędność w najlepszej cenie',
      description: 'System na profilu VEKA z pakietem trójszybowym. Doskonały stosunek ceny do parametrów termoizolacyjnych. Idealne dla nowego budownictwa.',
      features: ['Profil VEKA', 'Pakiet 3-szybowy', 'Energooszczędny', 'Gwarancja 10 lat'],
      image: '/images/produkty/passiv_line_plus.jpg',
      badge: 'POLECANY',
    },
    {
      id: 3,
      name: 'AdamS VEKA SL 82',
      tagline: 'Slim Look – więcej światła, mniej profilu',
      description: 'Smukłe profile 82mm z efektem Slim Look. Minimalistyczna rama optycznie powiększa okno i wpuszcza maksimum naturalnego światła.',
      features: ['Slim Look 82mm', 'Max. światło dzienne', 'Minimalistyczny design', 'System VEKA'],
      image: '/images/produkty/veka_sl_82.jpg',
      badge: null,
    },
    {
      id: 4,
      name: 'AdamS VEKA PF 70',
      tagline: 'Sprawdzony klasyk – niezawodny wybór',
      description: 'Klasyczny system 5-komorowy 70mm. Sprawdzony w tysiącach polskich domów. Szeroka dostępność kolorów i kształtów.',
      features: ['5 komór', '70mm głębokość', '100+ kolorów', 'System VEKA'],
      image: '/images/produkty/veka_pf_70.jpg',
      badge: null,
    },
    {
      id: 5,
      name: 'AdamS IDEAL 8000',
      tagline: 'Przełom – 8 komór, Uw ≤ 0,68 W/(m²K)',
      description: 'Innowacyjna konstrukcja 8-komorowa. Najlepsza izolacja akustyczna i termiczna w klasie. Dla wymagających inwestorów.',
      features: ['8 komór', 'Uw ≤ 0,68 W/(m²K)', 'Izolacja akustyczna', 'Premium'],
      image: '/images/produkty/ideal_8000.jpg',
      badge: 'NOWOŚĆ',
    },
    {
      id: 6,
      name: 'AdamS COMFORT LINE NEO',
      tagline: 'Zaokrąglone narożniki – ponadczasowy design',
      description: 'System z zaokrąglonymi narożnikami na profilu VEKA. Klasyczny wygląd pasujący do każdej architektury — od bloku po willę.',
      features: ['Zaokrąglone kształty', 'System VEKA', 'Szeroka paleta kolorów', 'Gwarancja 10 lat'],
      image: '/images/produkty/comfort_line_neo.webp',
      badge: null,
    },
    {
      id: 7,
      name: 'AdamS ELEGANT COMFORT-LINE',
      tagline: 'Prosta elegancja – premium design',
      description: 'Najwyższa półka estetyki z profili VEKA. Proste linie, perfekcyjne wykończenie. Dla tych, dla których wygląd jest tak samo ważny jak parametry.',
      features: ['Premium design', 'Proste linie', 'Antykorozyjność', 'System VEKA'],
      image: '/images/produkty/elegant_comfort_line.webp',
      badge: 'PREMIUM',
    },
  ],
  drzwi: [
    {
      id: 1,
      name: 'Drzwi HST – Podnoszono-Przesuwne',
      tagline: 'Do 6m szerokości – salon i taras jako jedna przestrzeń',
      description: 'System Hebeschiebesystem: unosi skrzydło przed przesunięciem. Niski próg ≤ 20mm, doskonała szczelność. Ogrom przeszklenia bez kompromisów.',
      features: ['Do 6m szerokości', 'Próg ≤ 20mm', 'Doskonała izolacja', 'System VEKA'],
      image: '/images/realizacje/DSC_1233-300x225.jpg',
      badge: 'BESTSELLER',
    },
    {
      id: 2,
      name: 'Drzwi PSK – Przesuwno-Uchylne',
      tagline: 'Klasyczny system z funkcją mikrowentylacji',
      description: 'Drzwi przesuwno-uchylne PSK: przesuwają się równolegle do ściany i można je uchylić do wietrzenia. Sprawdzony wybór do każdego tarasu.',
      features: ['Mikrowentylacja', 'Antyinfiltracyjne', 'Gładki ruch', 'System VEKA'],
      image: '/images/realizacje/DSC_1284-300x225.jpg',
      badge: null,
    },
    {
      id: 3,
      name: 'Drzwi Składane Harmonijkowe',
      tagline: 'Otwierasz całą ścianę – 100% wolnej przestrzeni',
      description: 'Drzwi harmonijkowe składające się na bok. Idealne do połączenia salonu z tarasem lub ogrodem. Efekt WOW gwarantowany.',
      features: ['100% otwarcia', 'Minimalny próg', 'Modułowe', 'Efekt WOW'],
      image: '/images/realizacje/DSC_1222-300x225.jpg',
      badge: 'NOWOŚĆ',
    },
    {
      id: 4,
      name: 'Drzwi Zewnętrzne Vikking',
      tagline: 'Stalowe, antywłamaniowe – klasa RC3',
      description: 'Drzwi wejściowe marki Vikking ze stali ocynkowanej. Certyfikat antywłamaniowy RC3. 50+ modeli, bogata paleta kolorów RAL.',
      features: ['Klasa RC3', 'Stal ocynkowana', '50+ modeli', 'Gwarancja 5 lat'],
      image: '/images/realizacje/DSC_1240-300x145.jpg',
      badge: 'BEZPIECZEŃSTWO',
    },
    {
      id: 5,
      name: 'Drzwi Przesuwne (Sliding)',
      tagline: 'Minimalizm – mechanizm ukryty w ścianie',
      description: 'System jezdny chowany w ścianie lub zewnętrzny. Cichy bieg na łożyskach kulkowych, do 3m wysokości skrzydła. Nowoczesne wnętrza.',
      features: ['Ukryty w ścianie', 'Cichy bieg', 'Do 3m wys.', 'Nowoczesny design'],
      image: '/images/realizacje/DSC_1292-300x171.jpg',
      badge: null,
    },
  ],
  rolety: [
    {
      id: 1,
      name: 'Rolety Zewnętrzne Aluprof',
      tagline: 'Ochrona przed słońcem, włamaniem i hałasem',
      description: 'Aluminiowe rolety zewnętrzne Aluprof montowane nadokiennie lub podtynkowo. Sterowanie ręczne, elektryczne lub Smart Home (Wi-Fi). Izolacja termiczna latem i zimą.',
      features: ['System Aluprof', 'Smart Home ready', 'Podtynkowe/nadokienne', 'Izolacja termiczna'],
      image: '/images/realizacje/DSC_1214-300x225.jpg',
      badge: 'POLECANE',
    },
    {
      id: 2,
      name: 'Rolety Wewnętrzne',
      tagline: 'Prywatność i styl w każdym pomieszczeniu',
      description: 'Eleganckie rolety wewnętrzne w szerokiej gamie tkanin: zaciemniające (blackout), półprzezroczyste i screen. Dopasowanie koloru do wnętrza.',
      features: ['100+ tkanin', 'Blackout dostępny', 'Łatwy montaż', 'Dopasowanie kolorów'],
      image: '/images/realizacje/DSC_1233-300x225.jpg',
      badge: null,
    },
    {
      id: 3,
      name: 'Rolety Screen',
      tagline: 'Widzisz na zewnątrz – nikt nie widzi do środka',
      description: 'Tkanina screen przepuszcza światło i widok, blokuje nasłonecznienie i wzrok z zewnątrz. Ochrona UV 90%. Idealne do biur, salonów, okien od południa.',
      features: ['Widok na zewnątrz', 'UV ochrona 90%', 'Redukuje nagrzewanie', 'Biura i domy'],
      image: '/images/realizacje/DSC_1292-300x171.jpg',
      badge: 'HIT',
    },
  ],
};

export const stats = [
  { value: 25, suffix: '+', label: 'lat doświadczenia' },
  { value: 500, suffix: '+', label: 'zrealizowanych montaży' },
  { value: 7, suffix: '', label: 'systemów okiennych' },
  { value: 100, suffix: '%', label: 'zadowolonych klientów' },
];

export const testimonials = [
  {
    id: 1,
    name: 'Marek Kowalski',
    location: 'Szczecin, os. Majowe',
    text: 'Wymiana okien w całym domu przebiegła sprawnie i profesjonalnie. Ekipa BT-Styl zrobiła wszystko w ciągu jednego dnia. Okna VEKA to zupełnie inny komfort – cisza, ciepło i piękny wygląd.',
    rating: 5,
    date: 'Marzec 2024',
  },
  {
    id: 2,
    name: 'Anna Nowak',
    location: 'Szczecin, Dąbie',
    text: 'Bardzo polecam! Fachowe doradztwo, uczciwe ceny i terminowa realizacja. Drzwi tarasowe HST to był strzał w dziesiątkę – ogród i salon stały się jedną przestrzenią.',
    rating: 5,
    date: 'Styczeń 2024',
  },
  {
    id: 3,
    name: 'Piotr Wiśniewski',
    location: 'Szczecin, Niebuszewo',
    text: 'Świetna obsługa od A do Z. Pan z salonu przyszedł na pomiar, wyjaśnił wszystkie opcje i nie namawiał na droższe rozwiązania. Okna Passiv-Line ULTRA – super wybór do nowego domu energooszczędnego.',
    rating: 5,
    date: 'Listopad 2023',
  },
  {
    id: 4,
    name: 'Katarzyna Zielińska',
    location: 'Szczecin-Prawobrzeże',
    text: 'Rolety zewnętrzne Aluprof polecone przez BT-Styl to strzał w dziesiątkę. Latem jest o wiele chłodniej, rachunki za klimatyzację spadły. Montaż ekspresowy, ekipa czysta i solidna.',
    rating: 5,
    date: 'Sierpień 2023',
  },
];

export const realizacje = [
  { id: 1, src: '/images/realizacje/DSC_1222-300x225.jpg', alt: 'Wymiana okien – dom jednorodzinny Szczecin' },
  { id: 2, src: '/images/realizacje/DSC_1214-300x225.jpg', alt: 'Okna PCV VEKA – apartament Szczecin' },
  { id: 3, src: '/images/realizacje/DSC_1233-300x225.jpg', alt: 'Drzwi tarasowe HST – ogród zimowy' },
  { id: 4, src: '/images/realizacje/DSC_1240-300x145.jpg', alt: 'Rolety zewnętrzne Aluprof montaż Szczecin' },
  { id: 5, src: '/images/realizacje/DSC_1292-300x171.jpg', alt: 'Okna aluminiowe – budynek komercyjny' },
  { id: 6, src: '/images/realizacje/DSC_1284-300x225.jpg', alt: 'Drzwi wejściowe Vikking montaż' },
  { id: 7, src: '/images/realizacje/20120705636-247x300.jpg', alt: 'Realizacja okienna – blok Szczecin' },
];

export const partners = [
  { name: 'VEKA', description: 'Lider systemów PVC' },
  { name: 'AdamS', description: 'Producent okien PVC' },
  { name: 'Vikking', description: 'Drzwi stalowe' },
  { name: 'Aluprof', description: 'Systemy aluminiowe' },
  { name: 'Barański', description: 'Drzwi zewnętrzne' },
];

export const contact = {
  address: 'ul. Bagienna 6, 70-772 Szczecin',
  phone: '91 454-09-99',
  mobile: '791-370-361',
  email: 'biuro@dobreoknaszczecin.pl',
  hours: {
    weekdays: 'Pon–Pt: 9:00–17:00',
    saturday: 'Sob: 9:00–13:00',
    sunday: 'Niedziela: zamknięte',
  },
};
