export const products = {
  okna: [
    {
      id: 1,
      name: 'AdamS PASSIV-LINE ULTRA',
      tagline: 'Dom pasywny – Uw do 0,54 W/(m²K)',
      description: 'System 6-komorowy z dociepleniem, głębokość 85mm. Wklejane szyby, wypełnienie pianą PU, wzmocnienia Ultradur (BASF). Pakiet 3- lub 4-szybowy z kryptonem.',
      features: ['85mm głębokość', 'Uw ≤ 0,54 W/(m²K)', '4-szybowy pakiet', 'Dom pasywny'],
      image: '/images/produkty/passiv_line_ultra.jpg',
      badge: 'BESTSELLER',
    },
    {
      id: 2,
      name: 'AdamS Passiv-Line PLUS',
      tagline: 'Energooszczędność w najlepszej cenie',
      description: 'System na profilu VEKA z pakietem trójszybowym. Doskonały stosunek ceny do parametrów termoizolacyjnych. Idealne dla nowego budownictwa.',
      features: ['Profil VEKA', 'Pakiet 3-szybowy', 'Energooszczędny', 'Gwarancja'],
      image: '/images/produkty/passiv_line_plus.jpg',
      badge: 'POLECANY',
    },
    {
      id: 3,
      name: 'AdamS VEKA SL 82',
      tagline: 'Slim Look – więcej światła, mniej profilu',
      description: 'Smukłe profile 82mm z efektem Slim Look. Minimalistyczna rama optycznie powiększa okno i wpuszcza maksimum naturalnego światła.',
      features: ['Slim Look 82mm', 'Max. światło dzienne', 'Minimalistyczny design', 'System VEKA'],
      image: '/images/produkty/veka_sl_82.jpg',
      badge: null,
    },
    {
      id: 4,
      name: 'AdamS VEKA PF 70',
      tagline: 'Sprawdzony klasyk – niezawodny wybór',
      description: 'Klasyczny system 5-komorowy 70mm. Sprawdzony w tysiącach polskich domów. Szeroka dostępność kolorów i kształtów.',
      features: ['5 komór', '70mm głębokość', '100+ kolorów', 'System VEKA'],
      image: '/images/produkty/veka_pf_70.jpg',
      badge: null,
    },
    {
      id: 5,
      name: 'AdamS IDEAL 8000',
      tagline: 'Przełom – 8 komór, Uw ≤ 0,68 W/(m²K)',
      description: 'Innowacyjna konstrukcja 8-komorowa. Najlepsza izolacja akustyczna i termiczna w klasie. Dla wymagających inwestorów.',
      features: ['8 komór', 'Uw ≤ 0,68 W/(m²K)', 'Izolacja akustyczna', 'Premium'],
      image: '/images/produkty/ideal_8000.jpg',
      badge: 'NOWOŚĆ',
    },
    {
      id: 6,
      name: 'AdamS COMFORT LINE NEO',
      tagline: 'Zaokrąglone narożniki – ponadczasowy design',
      description: 'System z zaokrąglonymi narożnikami na profilu VEKA. Klasyczny wygląd pasujący do każdej architektury — od bloku po willę.',
      features: ['Zaokrąglone kształty', 'System VEKA', 'Szeroka paleta kolorów', 'Gwarancja'],
      image: '/images/produkty/comfort_line_neo.webp',
      badge: null,
    },
    {
      id: 7,
      name: 'AdamS ELEGANT COMFORT-LINE',
      tagline: 'Prosta elegancja – premium design',
      description: 'Najwyższa półka estetyki z profili VEKA. Proste linie, perfekcyjne wykończenie. Dla tych, dla których wygląd jest tak samo ważny jak parametry.',
      features: ['Premium design', 'Proste linie', 'Antykorozyjność', 'System VEKA'],
      image: '/images/produkty/elegant_comfort_line.webp',
      badge: 'PREMIUM',
    },
  ],
  drzwi: [
    {
      id: 1,
      name: 'Drzwi HST – Podnoszono-Przesuwne',
      tagline: 'Do 6m szerokości – salon i taras jako jedna przestrzeń',
      description: 'System Hebeschiebesystem: unosi skrzydło przed przesunięciem. Niski próg ≤ 20mm, doskonała szczelność. Ogrom przeszklenia bez kompromisów.',
      features: ['Do 6m szerokości', 'Próg ≤ 20mm', 'Doskonała izolacja', 'System VEKA'],
      image: '/images/realizacje/DSC_1233-300x225.jpg',
      badge: 'BESTSELLER',
    },
    {
      id: 2,
      name: 'Drzwi PSK – Przesuwno-Uchylne',
      tagline: 'Klasyczny system z funkcją mikrowentylacji',
      description: 'Drzwi przesuwno-uchylne PSK: przesuwają się równolegle do ściany i można je uchylić do wietrzenia. Sprawdzony wybór do każdego tarasu.',
      features: ['Mikrowentylacja', 'Antyinfiltracyjne', 'Gładki ruch', 'System VEKA'],
      image: '/images/realizacje/DSC_1284-300x225.jpg',
      badge: null,
    },
    {
      id: 3,
      name: 'Drzwi Składane Harmonijkowe',
      tagline: 'Otwierasz całą ścianę – 100% wolnej przestrzeni',
      description: 'Drzwi harmonijkowe składające się na bok. Idealne do połączenia salonu z tarasem lub ogrodem. Efekt WOW gwarantowany.',
      features: ['100% otwarcia', 'Minimalny próg', 'Modułowe', 'Efekt WOW'],
      image: '/images/realizacje/DSC_1222-300x225.jpg',
      badge: 'NOWOŚĆ',
    },
    {
      id: 4,
      name: 'Drzwi Zewnętrzne Martom',
      tagline: 'Drzwi hybrydowe – lider rozwiązań łączących materiały',
      description: 'Drzwi stalowe marki Martom — lidera rozwiązań hybrydowych na polskim rynku. Opatentowana technologia łącząca drewno, stal, aluminium oraz zbrojone włóknem tworzywo ABS i piankę PUR.',
      features: ['Technologia hybrydowa', 'Drewno + stal + aluminium + ABS', 'Wypełnienie pianą PUR', 'Klasy odporności RC2 / RC3'],
      image: '/images/realizacje/DSC_1240-300x145.jpg',
      badge: 'BEZPIECZEŃSTWO',
    },
    {
      id: 5,
      name: 'Drzwi Przesuwne (Sliding)',
      tagline: 'Minimalizm – mechanizm ukryty w ścianie',
      description: 'System jezdny chowany w ścianie lub zewnętrzny. Cichy bieg na łożyskach kulkowych, do 3m wysokości skrzydła. Nowoczesne wnętrza.',
      features: ['Ukryty w ścianie', 'Cichy bieg', 'Do 3m wys.', 'Nowoczesny design'],
      image: '/images/realizacje/DSC_1292-300x171.jpg',
      badge: null,
    },
  ],
  rolety: [
    {
      id: 1,
      name: 'Rolety Zewnętrzne Aluprof',
      tagline: 'Ochrona przed słońcem, włamaniem i hałasem',
      description: 'Aluminiowe rolety zewnętrzne Aluprof montowane nadokiennie lub podtynkowo. Sterowanie ręczne, elektryczne lub Smart Home (Wi-Fi). Izolacja termiczna latem i zimą.',
      features: ['System Aluprof', 'Smart Home ready', 'Podtynkowe/nadokienne', 'Izolacja termiczna'],
      image: '/images/realizacje/DSC_1214-300x225.jpg',
      badge: 'POLECANE',
    },
    {
      id: 2,
      name: 'Rolety Wewnętrzne',
      tagline: 'Prywatność i styl w każdym pomieszczeniu',
      description: 'Eleganckie rolety wewnętrzne w szerokiej gamie tkanin: zaciemniające (blackout), półprzezroczyste i screen. Dopasowanie koloru do wnętrza.',
      features: ['100+ tkanin', 'Blackout dostępny', 'Łatwy montaż', 'Dopasowanie kolorów'],
      image: '/images/realizacje/DSC_1233-300x225.jpg',
      badge: null,
    },
    {
      id: 3,
      name: 'Rolety Screen',
      tagline: 'Widzisz na zewnątrz – nikt nie widzi do środka',
      description: 'Tkanina screen przepuszcza światło i widok, blokuje nasłonecznienie i wzrok z zewnątrz. Ochrona UV 90%. Idealne do biur, salonów, okien od południa.',
      features: ['Widok na zewnątrz', 'UV ochrona 90%', 'Redukuje nagrzewanie', 'Biura i domy'],
      image: '/images/realizacje/DSC_1292-300x171.jpg',
      badge: 'HIT',
    },
  ],
};

export const stats = [
  { value: 25, suffix: '+', label: 'lat doświadczenia' },
  { value: 500, suffix: '+', label: 'zrealizowanych montaży' },
  { value: 7, suffix: '', label: 'systemów okiennych' },
  { value: 100, suffix: '%', label: 'zadowolonych klientów' },
];

export const testimonials = [
  {
    id: 1,
    name: 'Marek Kowalski',
    location: 'Szczecin, os. Majowe',
    text: 'Wymiana okien w całym domu przebiegła sprawnie i profesjonalnie. Ekipa BT-Styl zrobiła wszystko w ciągu jednego dnia. Okna VEKA to zupełnie inny komfort – cisza, ciepło i piękny wygląd.',
    rating: 5,
    date: 'Marzec 2024',
  },
  {
    id: 2,
    name: 'Anna Nowak',
    location: 'Szczecin, Dąbie',
    text: 'Bardzo polecam! Fachowe doradztwo, uczciwe ceny i terminowa realizacja. Drzwi tarasowe HST to był strzał w dziesiątkę – ogród i salon stały się jedną przestrzenią.',
    rating: 5,
    date: 'Styczeń 2024',
  },
  {
    id: 3,
    name: 'Piotr Wiśniewski',
    location: 'Szczecin, Niebuszewo',
    text: 'Świetna obsługa od A do Z. Pan z salonu przyszedł na pomiar, wyjaśnił wszystkie opcje i nie namawiał na droższe rozwiązania. Okna Passiv-Line ULTRA – super wybór do nowego domu energooszczędnego.',
    rating: 5,
    date: 'Listopad 2023',
  },
  {
    id: 4,
    name: 'Katarzyna Zielińska',
    location: 'Szczecin-Prawobrzeże',
    text: 'Rolety zewnętrzne Aluprof polecone przez BT-Styl to strzał w dziesiątkę. Latem jest o wiele chłodniej, rachunki za klimatyzację spadły. Montaż ekspresowy, ekipa czysta i solidna.',
    rating: 5,
    date: 'Sierpień 2023',
  },
];

export const realizacje = [
  { id: 1, src: '/images/realizacje/real-01-4323594824461639807.webp', alt: 'Okna szczytowe w domu jednorodzinnym', width: 900, height: 1200 },
  { id: 2, src: '/images/realizacje/real-02-1780684701313103552.webp', alt: 'Drzwi zewnętrzne w kolorze niebieskim', width: 480, height: 640 },
  { id: 3, src: '/images/realizacje/real-03-20101001032.webp', alt: 'Okna w domu z bali drewnianych', width: 1200, height: 900 },
  { id: 4, src: '/images/realizacje/real-04-20110206204.webp', alt: 'Okno łukowe w elewacji z ceglaną opaską', width: 1200, height: 900 },
  { id: 5, src: '/images/realizacje/real-05-20110206205.webp', alt: 'Dom z drewnianą altaną i drzwiami wejściowymi', width: 1200, height: 900 },
  { id: 6, src: '/images/realizacje/real-06-20111122377.webp', alt: 'Drzwi drewniane w elewacji z klinkieru', width: 900, height: 1200 },
  { id: 7, src: '/images/realizacje/real-07-20111212390.webp', alt: 'Okno szprosowe w elewacji tynkowanej', width: 1200, height: 900 },
  { id: 8, src: '/images/realizacje/real-08-20111212392.webp', alt: 'Okna szprosowe w salonie', width: 1200, height: 900 },
  { id: 9, src: '/images/realizacje/real-09-20120705636.webp', alt: 'Zabudowa okien w kamienicy z werandą', width: 987, height: 1200 },
  { id: 10, src: '/images/realizacje/real-10-20120705637.webp', alt: 'Ogród zimowy — przeszklenie narożne', width: 900, height: 1200 },
  { id: 11, src: '/images/realizacje/real-11-20190207-142327.webp', alt: 'Dom z zadaszonym tarasem i oknami dachowymi', width: 1200, height: 900 },
  { id: 12, src: '/images/realizacje/real-12-20190207-142354.webp', alt: 'Drzwi wejściowe z przeszkleniem, kolor drewna', width: 900, height: 1200 },
  { id: 13, src: '/images/realizacje/real-13-20190224-092726.webp', alt: 'Okna antracytowe w nowoczesnym domu', width: 1200, height: 900 },
  { id: 14, src: '/images/realizacje/real-14-20190224-092751.webp', alt: 'Elewacja z oknami w ciemnej stolarce', width: 1200, height: 900 },
  { id: 15, src: '/images/realizacje/real-15-20190329-093351.webp', alt: 'Dom z garażem — okna i drzwi antracytowe', width: 1200, height: 900 },
  { id: 16, src: '/images/realizacje/real-16-20190430-113824.webp', alt: 'Okna narożne w domu z ciemnym dachem', width: 1200, height: 900 },
  { id: 17, src: '/images/realizacje/real-17-20250307-121929.webp', alt: 'Przeszklona weranda w konstrukcji aluminiowej', width: 1200, height: 900 },
  { id: 18, src: '/images/realizacje/real-18-2696921527815012970.webp', alt: 'Drzwi wejściowe z naświetlem łukowym', width: 480, height: 639 },
  { id: 19, src: '/images/realizacje/real-19-dsc04877.webp', alt: 'Drzwi zewnętrzne białe z przeszkleniami', width: 900, height: 1200 },
  { id: 20, src: '/images/realizacje/real-20-dsc04878.webp', alt: 'Drzwi wejściowe białe z panelami', width: 900, height: 1200 },
  { id: 21, src: '/images/realizacje/real-21-dsc05267.webp', alt: 'Dom parterowy z dużymi oknami', width: 1200, height: 774 },
  { id: 22, src: '/images/realizacje/real-22-dsc05274.webp', alt: 'Elewacja z klinkieru i okna w kolorze brązowym', width: 1200, height: 900 },
  { id: 23, src: '/images/realizacje/real-23-dsc05276.webp', alt: 'Okna w domu z cegły licowej', width: 1200, height: 900 },
  { id: 24, src: '/images/realizacje/real-24-dsc05419.webp', alt: 'Okna z drewnianymi okiennicami', width: 1200, height: 900 },
  { id: 25, src: '/images/realizacje/real-25-dsc05421.webp', alt: 'Dom z okiennicami — widok elewacji', width: 1200, height: 900 },
  { id: 26, src: '/images/realizacje/real-26-dsc05423.webp', alt: 'Okna z okiennicami w elewacji z cegły', width: 1200, height: 900 },
  { id: 27, src: '/images/realizacje/real-27-dsc05727.webp', alt: 'Dom parterowy z oknami tarasowymi', width: 640, height: 480 },
  { id: 28, src: '/images/realizacje/real-28-dsc06159.webp', alt: 'Dom pod strzechą — okna drewniane', width: 1200, height: 900 },
  { id: 29, src: '/images/realizacje/real-29-dsc06172.webp', alt: 'Okno łukowe w elewacji z klinkieru', width: 1200, height: 900 },
  { id: 30, src: '/images/realizacje/real-30-dsc06412.webp', alt: 'Dom parterowy z garażem — stolarka brązowa', width: 1200, height: 736 },
  { id: 31, src: '/images/realizacje/real-31-dsc06413.webp', alt: 'Dom z lukarną i oknem łukowym', width: 1200, height: 757 },
  { id: 32, src: '/images/realizacje/real-32-dsc07577.webp', alt: 'Okna w domu z cegły z czerwonym dachem', width: 1200, height: 900 },
  { id: 33, src: '/images/realizacje/real-33-dsc-1216.webp', alt: 'Dom jednorodzinny — okna i brama garażowa', width: 1200, height: 900 },
  { id: 34, src: '/images/realizacje/real-34-dsc-1270.webp', alt: 'Dom z oknami dachowymi i antracytową stolarką', width: 1200, height: 819 },
  { id: 35, src: '/images/realizacje/real-35-dsc-1275.webp', alt: 'Okna pasmowe w nowoczesnej bryle', width: 1200, height: 802 },
  { id: 36, src: '/images/realizacje/real-36-dsc-1372.webp', alt: 'Okno trójkątne w domu z bali', width: 1200, height: 900 },
  { id: 37, src: '/images/realizacje/real-37-dsc-1501.webp', alt: 'Duże przeszklenia w domu z panelami fotowoltaicznymi', width: 1200, height: 900 },
  { id: 38, src: '/images/realizacje/real-38-dsc-1692.webp', alt: 'Okno panoramiczne w elewacji z cegły', width: 1200, height: 900 },
  { id: 39, src: '/images/realizacje/real-39-dsc-1711.webp', alt: 'Okna i drzwi tarasowe w stolarce drewnianej', width: 1200, height: 900 },
  { id: 40, src: '/images/realizacje/real-40-dsc-1836.webp', alt: 'Dom z oknami w ciemnej stolarce — narożnik', width: 1200, height: 900 },
  { id: 41, src: '/images/realizacje/real-41-dsc-1839.webp', alt: 'Dom parterowy z zadaszonym wejściem', width: 1200, height: 900 },
  { id: 42, src: '/images/realizacje/real-42-dsc-1851.webp', alt: 'Przeszklenie panoramiczne — budynek nowoczesny', width: 1200, height: 900 },
  { id: 43, src: '/images/realizacje/real-43-dsc-1873.webp', alt: 'Dom parterowy z ciemnym dachem i oknami', width: 1200, height: 900 },
  { id: 44, src: '/images/realizacje/real-44-dsc-1875.webp', alt: 'Dom z garażem — okna antracytowe', width: 1200, height: 709 },
  { id: 45, src: '/images/realizacje/real-45-dsc-1884.webp', alt: 'Okna w nowoczesnej bryle z płaskim dachem', width: 1200, height: 741 },
  { id: 46, src: '/images/realizacje/real-46-dsc-2039.webp', alt: 'Duże przeszklenia w domu z płaskim dachem', width: 1200, height: 900 },
  { id: 47, src: '/images/realizacje/real-47-dsc-2127.webp', alt: 'Dom z tarasem i drzwiami przesuwnymi', width: 1200, height: 900 },
  { id: 48, src: '/images/realizacje/real-48-dsc-2206.webp', alt: 'Elewacja z kamieniem dekoracyjnym i oknami', width: 1200, height: 900 },
  { id: 49, src: '/images/realizacje/real-49-img-20250709-wa0011.webp', alt: 'Drzwi wejściowe czerwone w ceglanym portalu', width: 900, height: 1200 },
  { id: 50, src: '/images/realizacje/real-50-img-20250926-wa0001.webp', alt: 'Drzwi wejściowe w kolorze wiśni', width: 900, height: 1200 },
  { id: 51, src: '/images/realizacje/real-51-img-0485.webp', alt: 'Dom z oknem łukowym i przeszkleniami', width: 1200, height: 900 },
  { id: 52, src: '/images/realizacje/real-52-img-0916.webp', alt: 'Dom z tarasem i dużymi przeszkleniami', width: 640, height: 480 },
  { id: 53, src: '/images/realizacje/real-53-img-20171005-102305.webp', alt: 'Dom z oknami szprosowymi — elewacja zielona', width: 1188, height: 1200 },
  { id: 54, src: '/images/realizacje/real-54-img-20171005-102333.webp', alt: 'Budynek z rzędem okien szprosowych', width: 1200, height: 1140 },
  { id: 55, src: '/images/realizacje/real-55-img-20191210-154850.webp', alt: 'Okna w nowoczesnym domu z płaskim dachem', width: 1200, height: 902 },
  { id: 56, src: '/images/realizacje/real-56-img-20200330-112049.webp', alt: 'Drzwi drewniane dwuskrzydłowe', width: 902, height: 1200 },
  { id: 57, src: '/images/realizacje/real-57-img-20210420-110148.webp', alt: 'Drzwi białe z naświetlem w portalu z cegły', width: 1200, height: 902 },
  { id: 58, src: '/images/realizacje/real-58-img-20220303-115250.webp', alt: 'Dom parterowy z garażem i oknami', width: 1200, height: 902 },
  { id: 59, src: '/images/realizacje/real-59-img-20230609-150644.webp', alt: 'Okno narożne w elewacji z drewnem', width: 1200, height: 902 },
  { id: 60, src: '/images/realizacje/real-60-img-5248.webp', alt: 'Dom w drewnianej elewacji — okna białe', width: 1200, height: 900 },
  { id: 61, src: '/images/realizacje/real-61-zdjecie-0024.webp', alt: 'Dom z balkonem — elewacja żółta', width: 1200, height: 900 },
  { id: 62, src: '/images/realizacje/real-62-zdjecie-0069.webp', alt: 'Dom z oknem łukowym w szczycie', width: 1200, height: 739 },
  { id: 63, src: '/images/realizacje/real-63-zdjecie0556.webp', alt: 'Okna szprosowe w domu z kamiennym cokołem', width: 1200, height: 900 },
  { id: 64, src: '/images/realizacje/real-64-zdjecie0559.webp', alt: 'Okno tarasowe białe — widok z wnętrza', width: 1200, height: 900 },
];

export const partners = [
  { name: 'VEKA', description: 'Lider systemów PVC' },
  { name: 'AdamS', description: 'Producent okien PVC' },
  { name: 'Martom', description: 'Drzwi hybrydowe' },
  { name: 'Aluprof', description: 'Systemy aluminiowe' },
  { name: 'Barański', description: 'Drzwi zewnętrzne' },
];

export const contact = {
  address: 'ul. Bagienna 6, 70-772 Szczecin',
  phone: '91 454-09-99',
  mobile: '791-370-361',
  email: 'info@btstyl.pl',
  hours: {
    weekdays: 'Pon–Pt: 9:00–17:00',
    saturday: 'Sob: 9:00–13:00',
    sunday: 'Niedziela: zamknięte',
  },
};
